##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.1.0] date: [Sun Dec 08 16:11:24 EST 2024] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = BLE_v2


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32wbaxx_it.c \
Core/Src/stm32wbaxx_hal_msp.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_cortex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_i2c.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_i2c_ex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rcc.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rcc_ex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_flash.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_flash_ex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_gpio.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_dma.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_dma_ex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_exti.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_pwr.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_pwr_ex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_gtzc.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_icache.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_hsem.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_uart.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_uart_ex.c \
Core/Src/system_stm32wbaxx.c \
Core/Src/app_entry.c \
Core/Src/app_threadx.c \
Core/Src/stm32wbaxx_hal_timebase_tim.c \
System/Modules/adc_ctrl.c \
System/Modules/app_sys.c \
System/Modules/ble_timer.c \
System/Modules/otp.c \
System/Modules/scm.c \
System/Modules/stm_list.c \
System/Modules/baes/baes_cmac.c \
System/Modules/baes/baes_ecb.c \
System/Modules/MemoryManager/advanced_memory_manager.c \
System/Modules/MemoryManager/stm32_mm.c \
System/Modules/Nvm/nvm_emul.c \
System/Modules/RTDebug/RTDebug.c \
System/Modules/RTDebug/RTDebug_dtb.c \
System/Modules/RFControl/rf_antenna_switch.c \
System/Modules/Flash/flash_driver.c \
System/Modules/Flash/flash_manager.c \
System/Modules/Flash/rf_timing_synchro.c \
System/Modules/Flash/simple_nvm_arbiter.c \
System/Interfaces/hw_aes.c \
System/Interfaces/hw_otp.c \
System/Interfaces/hw_pka.c \
System/Interfaces/hw_rng.c \
System/Interfaces/pka_p256.c \
System/Interfaces/stm32_lpm_if.c \
System/Interfaces/timer_if.c \
System/Interfaces/usart_if.c \
System/Config/LowPower/user_low_power_config.c \
System/Config/Debug_GPIO/app_debug.c \
STM32_WPAN/App/app_ble.c \
STM32_WPAN/App/hrs.c \
STM32_WPAN/App/hrs_app.c \
STM32_WPAN/App/dis.c \
STM32_WPAN/App/dis_app.c \
STM32_WPAN/Target/bleplat.c \
STM32_WPAN/Target/power_table.c \
STM32_WPAN/Target/linklayer_plat.c \
STM32_WPAN/Target/bpka.c \
STM32_WPAN/Target/ll_sys_if.c \
STM32_WPAN/Target/host_stack_if.c \
AZURE_RTOS/App/app_azure_rtos.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_tim.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_tim_ex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_adc.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_adc_ex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_crc.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_crc_ex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_ramcfg.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rng.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rng_ex.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rtc.c \
Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rtc_ex.c \
Middlewares/ST/STM32_WPAN/ble/svc/Src/svc_ctl.c \
Middlewares/ST/STM32_WPAN/link_layer/ll_sys/src/ll_sys_cs.c \
Middlewares/ST/STM32_WPAN/link_layer/ll_sys/src/ll_sys_dp_slp.c \
Middlewares/ST/STM32_WPAN/link_layer/ll_sys/src/ll_sys_intf.c \
Middlewares/ST/STM32_WPAN/link_layer/ll_sys/src/ll_sys_startup.c \
Middlewares/ST/threadx/common/src/tx_initialize_high_level.c \
Middlewares/ST/threadx/common/src/tx_initialize_kernel_enter.c \
Middlewares/ST/threadx/common/src/tx_initialize_kernel_setup.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_error_handler.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_error_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_system_resume.c \
Middlewares/ST/threadx/common/src/tx_block_allocate.c \
Middlewares/ST/threadx/common/src/tx_block_pool_cleanup.c \
Middlewares/ST/threadx/common/src/tx_block_pool_create.c \
Middlewares/ST/threadx/common/src/tx_block_pool_delete.c \
Middlewares/ST/threadx/common/src/tx_block_pool_info_get.c \
Middlewares/ST/threadx/common/src/tx_block_pool_initialize.c \
Middlewares/ST/threadx/common/src/tx_block_pool_prioritize.c \
Middlewares/ST/threadx/common/src/tx_block_release.c \
Middlewares/ST/threadx/common/src/tx_byte_allocate.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_cleanup.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_create.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_delete.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_info_get.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_initialize.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_prioritize.c \
Middlewares/ST/threadx/common/src/tx_byte_pool_search.c \
Middlewares/ST/threadx/common/src/tx_byte_release.c \
Middlewares/ST/threadx/common/src/tx_event_flags_cleanup.c \
Middlewares/ST/threadx/common/src/tx_event_flags_create.c \
Middlewares/ST/threadx/common/src/tx_event_flags_delete.c \
Middlewares/ST/threadx/common/src/tx_event_flags_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_info_get.c \
Middlewares/ST/threadx/common/src/tx_event_flags_initialize.c \
Middlewares/ST/threadx/common/src/tx_event_flags_set.c \
Middlewares/ST/threadx/common/src/tx_event_flags_set_notify.c \
Middlewares/ST/threadx/common/src/tx_mutex_cleanup.c \
Middlewares/ST/threadx/common/src/tx_mutex_create.c \
Middlewares/ST/threadx/common/src/tx_mutex_delete.c \
Middlewares/ST/threadx/common/src/tx_mutex_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_info_get.c \
Middlewares/ST/threadx/common/src/tx_mutex_initialize.c \
Middlewares/ST/threadx/common/src/tx_mutex_prioritize.c \
Middlewares/ST/threadx/common/src/tx_mutex_priority_change.c \
Middlewares/ST/threadx/common/src/tx_mutex_put.c \
Middlewares/ST/threadx/common/src/tx_queue_cleanup.c \
Middlewares/ST/threadx/common/src/tx_queue_create.c \
Middlewares/ST/threadx/common/src/tx_queue_delete.c \
Middlewares/ST/threadx/common/src/tx_queue_flush.c \
Middlewares/ST/threadx/common/src/tx_queue_front_send.c \
Middlewares/ST/threadx/common/src/tx_queue_info_get.c \
Middlewares/ST/threadx/common/src/tx_queue_initialize.c \
Middlewares/ST/threadx/common/src/tx_queue_prioritize.c \
Middlewares/ST/threadx/common/src/tx_queue_receive.c \
Middlewares/ST/threadx/common/src/tx_queue_send.c \
Middlewares/ST/threadx/common/src/tx_queue_send_notify.c \
Middlewares/ST/threadx/common/src/tx_semaphore_ceiling_put.c \
Middlewares/ST/threadx/common/src/tx_semaphore_cleanup.c \
Middlewares/ST/threadx/common/src/tx_semaphore_create.c \
Middlewares/ST/threadx/common/src/tx_semaphore_delete.c \
Middlewares/ST/threadx/common/src/tx_semaphore_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_info_get.c \
Middlewares/ST/threadx/common/src/tx_semaphore_initialize.c \
Middlewares/ST/threadx/common/src/tx_semaphore_prioritize.c \
Middlewares/ST/threadx/common/src/tx_semaphore_put.c \
Middlewares/ST/threadx/common/src/tx_semaphore_put_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_create.c \
Middlewares/ST/threadx/common/src/tx_thread_delete.c \
Middlewares/ST/threadx/common/src/tx_thread_entry_exit_notify.c \
Middlewares/ST/threadx/common/src/tx_thread_identify.c \
Middlewares/ST/threadx/common/src/tx_thread_info_get.c \
Middlewares/ST/threadx/common/src/tx_thread_initialize.c \
Middlewares/ST/threadx/common/src/tx_thread_preemption_change.c \
Middlewares/ST/threadx/common/src/tx_thread_priority_change.c \
Middlewares/ST/threadx/common/src/tx_thread_relinquish.c \
Middlewares/ST/threadx/common/src/tx_thread_reset.c \
Middlewares/ST/threadx/common/src/tx_thread_resume.c \
Middlewares/ST/threadx/common/src/tx_thread_shell_entry.c \
Middlewares/ST/threadx/common/src/tx_thread_sleep.c \
Middlewares/ST/threadx/common/src/tx_thread_stack_analyze.c \
Middlewares/ST/threadx/common/src/tx_thread_suspend.c \
Middlewares/ST/threadx/common/src/tx_thread_system_preempt_check.c \
Middlewares/ST/threadx/common/src/tx_thread_system_suspend.c \
Middlewares/ST/threadx/common/src/tx_thread_terminate.c \
Middlewares/ST/threadx/common/src/tx_thread_time_slice.c \
Middlewares/ST/threadx/common/src/tx_thread_time_slice_change.c \
Middlewares/ST/threadx/common/src/tx_thread_timeout.c \
Middlewares/ST/threadx/common/src/tx_thread_wait_abort.c \
Middlewares/ST/threadx/common/src/tx_time_get.c \
Middlewares/ST/threadx/common/src/tx_time_set.c \
Middlewares/ST/threadx/common/src/txe_block_allocate.c \
Middlewares/ST/threadx/common/src/txe_block_pool_create.c \
Middlewares/ST/threadx/common/src/txe_block_pool_delete.c \
Middlewares/ST/threadx/common/src/txe_block_pool_info_get.c \
Middlewares/ST/threadx/common/src/txe_block_pool_prioritize.c \
Middlewares/ST/threadx/common/src/txe_block_release.c \
Middlewares/ST/threadx/common/src/txe_byte_allocate.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_create.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_delete.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_info_get.c \
Middlewares/ST/threadx/common/src/txe_byte_pool_prioritize.c \
Middlewares/ST/threadx/common/src/txe_byte_release.c \
Middlewares/ST/threadx/common/src/txe_event_flags_create.c \
Middlewares/ST/threadx/common/src/txe_event_flags_delete.c \
Middlewares/ST/threadx/common/src/txe_event_flags_get.c \
Middlewares/ST/threadx/common/src/txe_event_flags_info_get.c \
Middlewares/ST/threadx/common/src/txe_event_flags_set.c \
Middlewares/ST/threadx/common/src/txe_event_flags_set_notify.c \
Middlewares/ST/threadx/common/src/txe_mutex_create.c \
Middlewares/ST/threadx/common/src/txe_mutex_delete.c \
Middlewares/ST/threadx/common/src/txe_mutex_get.c \
Middlewares/ST/threadx/common/src/txe_mutex_info_get.c \
Middlewares/ST/threadx/common/src/txe_mutex_prioritize.c \
Middlewares/ST/threadx/common/src/txe_mutex_put.c \
Middlewares/ST/threadx/common/src/txe_queue_create.c \
Middlewares/ST/threadx/common/src/txe_queue_delete.c \
Middlewares/ST/threadx/common/src/txe_queue_flush.c \
Middlewares/ST/threadx/common/src/txe_queue_front_send.c \
Middlewares/ST/threadx/common/src/txe_queue_info_get.c \
Middlewares/ST/threadx/common/src/txe_queue_prioritize.c \
Middlewares/ST/threadx/common/src/txe_queue_receive.c \
Middlewares/ST/threadx/common/src/txe_queue_send.c \
Middlewares/ST/threadx/common/src/txe_queue_send_notify.c \
Middlewares/ST/threadx/common/src/txe_semaphore_ceiling_put.c \
Middlewares/ST/threadx/common/src/txe_semaphore_create.c \
Middlewares/ST/threadx/common/src/txe_semaphore_delete.c \
Middlewares/ST/threadx/common/src/txe_semaphore_get.c \
Middlewares/ST/threadx/common/src/txe_semaphore_info_get.c \
Middlewares/ST/threadx/common/src/txe_semaphore_prioritize.c \
Middlewares/ST/threadx/common/src/txe_semaphore_put.c \
Middlewares/ST/threadx/common/src/txe_semaphore_put_notify.c \
Middlewares/ST/threadx/common/src/txe_thread_create.c \
Middlewares/ST/threadx/common/src/txe_thread_delete.c \
Middlewares/ST/threadx/common/src/txe_thread_entry_exit_notify.c \
Middlewares/ST/threadx/common/src/txe_thread_info_get.c \
Middlewares/ST/threadx/common/src/txe_thread_preemption_change.c \
Middlewares/ST/threadx/common/src/txe_thread_priority_change.c \
Middlewares/ST/threadx/common/src/txe_thread_relinquish.c \
Middlewares/ST/threadx/common/src/txe_thread_reset.c \
Middlewares/ST/threadx/common/src/txe_thread_resume.c \
Middlewares/ST/threadx/common/src/txe_thread_suspend.c \
Middlewares/ST/threadx/common/src/txe_thread_terminate.c \
Middlewares/ST/threadx/common/src/txe_thread_time_slice_change.c \
Middlewares/ST/threadx/common/src/txe_thread_wait_abort.c \
Middlewares/ST/threadx/common/src/tx_timer_activate.c \
Middlewares/ST/threadx/common/src/tx_timer_change.c \
Middlewares/ST/threadx/common/src/tx_timer_create.c \
Middlewares/ST/threadx/common/src/tx_timer_deactivate.c \
Middlewares/ST/threadx/common/src/tx_timer_delete.c \
Middlewares/ST/threadx/common/src/tx_timer_expiration_process.c \
Middlewares/ST/threadx/common/src/tx_timer_info_get.c \
Middlewares/ST/threadx/common/src/tx_timer_initialize.c \
Middlewares/ST/threadx/common/src/tx_timer_system_activate.c \
Middlewares/ST/threadx/common/src/tx_timer_system_deactivate.c \
Middlewares/ST/threadx/common/src/tx_timer_thread_entry.c \
Middlewares/ST/threadx/common/src/txe_timer_activate.c \
Middlewares/ST/threadx/common/src/txe_timer_change.c \
Middlewares/ST/threadx/common/src/txe_timer_create.c \
Middlewares/ST/threadx/common/src/txe_timer_deactivate.c \
Middlewares/ST/threadx/common/src/txe_timer_delete.c \
Middlewares/ST/threadx/common/src/txe_timer_info_get.c \
Utilities/trace/adv_trace/stm32_adv_trace.c \
Utilities/misc/stm32_mem.c \
Utilities/misc/stm32_systime.c \
Utilities/misc/stm32_tiny_sscanf.c \
Utilities/misc/stm32_tiny_vsnprintf.c \
Utilities/tim_serv/stm32_timer.c \
Utilities/lpm/tiny_lpm/stm32_lpm.c

# ASM sources
ASM_SOURCES =  \
startup_stm32wba52xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 
-DTX_SINGLE_MODE_NON_SECURE=1

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32WBA52xx \
-DUSE_FULL_LL_DRIVER \
-DPHY_2_10_a \
-DPHY_40nm_2_30_a_A1 \
-DBLE \
-DTX_INCLUDE_USER_DEFINE_FILE \
-DTX_SINGLE_MODE_NON_SECURE=1


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32WBAxx_HAL_Driver/Inc \
-IDrivers/STM32WBAxx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32WBAxx/Include \
-IDrivers/CMSIS/Include \
-ISystem/Interfaces \
-ISystem/Modules \
-ISystem/Modules/baes \
-ISystem/Modules/Flash \
-ISystem/Modules/MemoryManager \
-ISystem/Modules/Nvm \
-ISystem/Modules/RTDebug \
-ISystem/Modules/RFControl \
-ISystem/Config/LowPower \
-ISystem/Config/Debug_GPIO \
-ISystem/Config/Flash \
-ISTM32_WPAN/App \
-ISTM32_WPAN/Target \
-IAZURE_RTOS/App \
-IUtilities/trace/adv_trace \
-IUtilities/misc \
-IUtilities/tim_serv \
-IUtilities/lpm/tiny_lpm \
-IMiddlewares/ST/STM32_WPAN \
-IMiddlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/config/ble_full \
-IMiddlewares/ST/STM32_WPAN/ble/svc/Src \
-IMiddlewares/ST/threadx/common/inc \
-IMiddlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc \
-IMiddlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc/_40nm_reg_files \
-IMiddlewares/ST/STM32_WPAN/link_layer/ll_sys/inc \
-IMiddlewares/ST/STM32_WPAN/ble \
-IMiddlewares/ST/STM32_WPAN/ble/stack/include \
-IMiddlewares/ST/STM32_WPAN/ble/stack/include/auto \
-IMiddlewares/ST/STM32_WPAN/ble/svc/Inc \
-IMiddlewares/ST/threadx/ports/cortex_m33/gnu/inc


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32WBA52xx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
